### ISSUE TITLE
Bump deno std and fix 1.9/deploy compatibility

### ISSUE THREAD

**Issue by eliassjogreen** [christophgysin/aws-sdk-js-v3#10]
## Describe the bug
When trying to use this module in the [`deployctl` cli](https://github.com/denoland/deployctl) I am getting a bunch of type errors most likely caused by old incompatible std versions. (This could also be an issue with deploy)

#### SDK version number
`v3.13.0.0`

## Details of the deno version
```
deno 1.9.0 (release, x86_64-pc-windows-msvc)
v8 9.1.269.5
typescript 4.2.2
```

I am using `1.9.0` instead of `1.9.1` because of compatibility issues with another module (`1.9.1` fully aligns `fetch`, so nothing you should have to worry about)

## Steps to reproduce
`deno cache --unstable deps.ts` or `deployctl `
```ts
export {
  DynamoDBClient,
  GetItemCommand,
  PutItemCommand,
  ScanCommand,
} from "https://deno.land/x/aws_sdk@v3.13.0.0/client-dynamodb/mod.ts";
export type { PutItemCommandOutput } from "https://deno.land/x/aws_sdk@v3.13.0.0/client-dynamodb/mod.ts";
```

#### Observed behavior
Various `TS2339 TS2339 [ERROR]: Property x does not exist on type 'typeof Deno'.` errors.

**Comment by christophgysin** [comment]
I'm unable to reproduce this:
```
$ deno --version
deno 1.9.0 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.5
typescript 4.2.2
```
```
$ deno cache --unstable deps.ts
Check file:///tmp/deps.ts
```
I also tried 1.9.1, works as expected.

AFAIK deno 1.9 should be compatible with older versions of std. Some APIs are deprecated and will go away in 2.0, but that shouldn't cause any issues with 1.9.0.

**Comment by eliassjogreen** [comment]
Must be deno deploy which is incompatible then... It looks like the problem is some uses of the `Deno` api which does not yet exist in the deploy evironment.

**Comment by christophgysin** [comment]
I'm happy to help an reopen this if you can update the steps so I can reproduce the issue.

**Comment by eliassjogreen** [comment]
After installing the [`deployctl` cli](https://github.com/denoland/deployctl) running `deployctl check deps.ts` it will result in 243 errors, all of them related to certain things deno has access to which deploy does not. I am currently using `https://cdn.skypack.dev/@aws-sdk/client-dynamodb@3.13.0` for my project but the typings do not work so I would like to switch over to this project.
