### ISSUE TITLE
Unable to publish due to new size limit in deno.land/x

### ISSUE THREAD

**Issue by christophgysin** [christophgysin/aws-sdk-js-v3#2]
It seems that [deno.land/x](https://deno.land/x) has [introduced a module limit of 20Mb](https://github.com/denoland/deno_registry2/pull/168) which [prevents publishing a new version](https://deno.land/status/5fb80c1f00fdae66003dab6c) of this module.

**Comment by paul-thompson-helix** [comment]
In the pr https://github.com/denoland/deno_registry2/pull/168 it seems it was intended to be a loosening of the restriction.
I think the people at denoland would want to support this, as opening up aws sdk would be a huge step forward.

**Comment by christophgysin** [comment]
I sent a mail to Ryan and got our quota increased to 200Mb.

**Comment by christophgysin** [comment]
We're now hitting an error in the registry. I [opened an issue](https://github.com/denoland/deno_registry2/issues/182).

**Comment by christophgysin** [comment]
Seems to work again 👍
