### ISSUE TITLE
This library is missing the `s3. getSignedUrl` api

### ISSUE THREAD

**Issue by justinmchase** [christophgysin/aws-sdk-js-v3#23]
## Describe the bug
This library is missing the `s3.getSignedUrl` api. These are functions that exist in the javascript API but are not actual server calls, and I am assuming this library is code generating the library somehow and therefore these functions are not part of this sdk.

#### SDK version number
`@aws-sdk/s3-client@v3.22.0-1`

## Details of the deno version
```
deno 1.11.5 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2
```

## Steps to reproduce
```
export { S3 } from 'https://deno.land/x/aws_sdk@v3.22.0-1/client-s3/S3.ts'
const s3 = new S3({ ... })
s3.getSignedUrl() // not defined
```

#### Observed behavior
The method is missing

#### Expected behavior
The method is expected to exist.

## Additional context
Here is the documentation on the api: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property

Here is a link to the function body:
https://github.com/aws/aws-sdk-js/blob/a2e71ca5154c442d9e330dbed1c66c3b34c680f1/lib/services/s3.js#L912

Also a few others that are similarly missing:
* getSignedUrl
* getSignedUrlPromise
* createPresignedPost

**Comment by christophgysin** [comment]
This is a fork of [aws/aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3), not [aws/aws-sdk-js](https://github.com/aws/aws-sdk-js) (v2).

There seems to be a discussion about this in https://github.com/aws/aws-sdk-js-v3/issues/456, specifically [this comment](https://github.com/aws/aws-sdk-js-v3/issues/456#issuecomment-568267394) and [this comment](https://github.com/aws/aws-sdk-js-v3/issues/456#issuecomment-761606460).

If some functionality is missing in [aws/aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3), please [report it upstream](https://github.com/aws/aws-sdk-js-v3/issues). If it is present upstream but broken in this deno port, feel free to open a new issue.

**Comment by justinmchase** [comment]
So you're saying its not on the s3 client but its here instead:
https://github.com/christophgysin/aws-sdk-js-v3/blob/deno/deno/s3-request-presigner/getSignedUrl.ts

**Comment by christophgysin** [comment]
That's the one, although I never tried using this with deno, so please report back if you find any bugs.
