### ISSUE TITLE
Still updating this package?

### ISSUE THREAD

**Issue by sjmueller** [christophgysin/aws-sdk-js-v3#26]
Recently aws updated https://github.com/aws/aws-sdk-js-crypto-helpers to `v2.0.0`, amongst many other changes. Meanwhile, package networks like `esm.sh` and `skypack` still don't handle aws correctly, so this lib is still very relevant.

@christophgysin do you have plans to continue keeping this repo up with aws+deno releases?

**Comment by christophgysin** [comment]
I do! I just haven't had much time to dedicate to this.

If you can help out, I'd love get this working in an AWS Lambda using a custom deno runtime. AFAIK that still doesn't work, and I haven't had the time to debug what exactly is the reason.

Another thing holding this back is the lack of a decent integration testsuite to verify all features still work after bumping the version. Currently I read the code changes and manuall run some examples. But that is time consuming and error prone.

**Comment by christophgysin** [comment]
@sjmueller  How is aws-sdk-js-crypto-helpers related?

**Comment by sjmueller** [comment]
Since opening this issue, `esm.sh` began to work properly without blowing up within `aws-sdk-js-crypto-helpers`. With this fork's new update we can now switch back to this lib, see how everything works, and report back.
