### ISSUE TITLE
Update missing properties (Filters) for SecretsManager.ListSecretsRequest

### ISSUE THREAD

**Issue by mrowles** [christophgysin/aws-sdk-js-v3#3]
**Is your feature request related to a problem? Please describe.**

I noticed SecretsManager > listSecrets request params are missing 'Filter' param, which is really useful for environments with a large list of secrets (described [here in the AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/list-secrets.html) and [here in the NodeJS/TS AWS SDK](https://github.com/aws/aws-sdk-js/blob/master/clients/secretsmanager.d.ts#L357)).

**Describe the solution you'd like**
```
import { SecretsManager } from 'https://deno.land/x/aws_sdk@v0.0.1/client-secrets-manager/SecretsManager.ts';
import {
  CreateSecretRequest,
  ListSecretsRequest,
  ListSecretsResponse,
  SecretListEntry,
  UpdateSecretRequest,
} from 'https://deno.land/x/aws_sdk@v0.0.1/client-secrets-manager/models/index.ts';

const listSecretsRequest: ListSecretsRequest = {
    // this errors out
    Filters: [{
        Key: 'name',
        Values: ['someSecretName'],
    }],
};

const existingSecretsResponse: ListSecretsResponse = await secretsManager.listSecrets(
    listSecretsRequest,
);
```

**Describe alternatives you've considered**

Right now, I am just getting the whole list and filtering after the fact in code.

**Additional context**

N/A

**Comment by christophgysin** [comment]
There seems to be a typo in your example. When adding the missing apostroph, the above works for me as expected.

Can you reproduce this with typo corrected? If so, can you provide a full example I can run, and the error you get?

**Comment by mrowles** [comment]
@christophgysin I have updated the code with the imports just to be sure

**Comment by christophgysin** [comment]
Can you try to reproduce this with the latest version v0.0.5?

**Comment by mrowles** [comment]
@christophgysin That worked thanks. I had to add the `--unstable` flag to the deno command. Legend!!!

**Comment by christophgysin** [comment]
Where does it recommend to use v0.0.1?

**Comment by mrowles** [comment]
@christophgysin It appears as though the default lands on v0.0.5 now, I'm not sure what I'm on about. Maybe it's just Google search results point at 0.0.1 :/ All good. Cheers for the help!
