### ISSUE TITLE
Invalid import in  https://deno.land/x/aws_sdk@v3.0.0.0/util-waiter/createWaiter.ts

### ISSUE THREAD

**Issue by fomalhaut79** [christophgysin/aws-sdk-js-v3#6]
**Describe the bug**
Invalid import `import { sleep, validateWaiterOptions } from "./utils.ts";
`
**_utils_** is a directory

**SDK version number**
v.3.0.0.0

**Comment by christophgysin** [comment]
Fixed in [v3.1.0.0](https://deno.land/x/aws_sdk@v3.1.0.0)
