### ISSUE TITLE
Broken dependency for body-checksum-node

### ISSUE THREAD

**Issue by jdfoster** [christophgysin/aws-sdk-js-v3#9]
## Describe the bug
When using the Glacier API an error is thrown for a missing function `createReadStream` for the `node/fs` deno standard library.

This bug appears to be due to the reliance on this `body_checksum_node` library within `aws_sdk@v3.4.1.0/client-glacier/runtimeConfig.ts`; this can be resolve locally by switching this dependency to `"https://jspm.dev/@aws-sdk/body-checksum-browser"`. I have attempted to resolve this in an PR to add an additional pattern matcher to the `copy-to-deno` script, but alas I haven't been able to successfully (re)generate the patched services with the snippet below.

```js
    if (line === 'import { bodyChecksumGenerator } from "../body-checksum-node/mod.ts";') {
      output.push('import { bodyChecksumGenerator } from "https://jspm.dev/@aws-sdk/body-checksum-browser";');
      continue;
    }
```

#### SDK version number
`aws_sdk@v3.4.1.0/client-glacier`

## Details of the deno version
```
deno 1.7.1 (release, x86_64-unknown-linux-gnu)
v8 8.9.255.3
typescript 4.1.3
```

## Steps to reproduce
```js
import {
  GlacierClient,
  ListVaultsCommand,
} from "https://deno.land/x/aws_sdk@v3.4.1.0/client-glacier/mod.ts";

const accountId = "AWS_ACCOUNT_ID";

const client = new GlacierClient({});
const command = new ListVaultsCommand({ accountId });
const data = await client.send(command);

console.log(data);
```
#### Observed behavior
```
error: TS2614 [ERROR]: Module '"https://deno.land/std@0.79.0/node/fs.ts"' has no exported member 'createReadStream'. Did you mean to use 'import createReadStream from "https://deno.land/std@0.79.0/node/fs.ts"' instead?
import { createReadStream } from "https://deno.land/std@0.79.0/node/fs.ts";
         ~~~~~~~~~~~~~~~~
    at https://deno.land/x/aws_sdk@v3.4.1.0/body-checksum-node/mod.ts:6:10
```

#### Expected behavior
The code snippet above is expected to print the output from the _ListVaultsCommand_.

**Comment by christophgysin** [comment]
Thanks for the bug report! This should be fixed in [3.4.1.1](https://deno.land/x/aws_sdk@v3.4.1.1).
